improved error handling

diff --git a/prof b/prof
--- a/prof
+++ b/prof
@@ -46,7 +46,6 @@
 #
 ################################################################################
 
-
 profile_template=$(cat << EOF
 #!/usr/bin/env bash
 
@@ -89,28 +88,31 @@ echo "Profile {profile_name} loaded."
 EOF
 )
 
+die() {
+    if [ -n "$1" ]; then
+        echo "$1" >&2
+    fi
+    if [ -n "$2" ]; then
+        echo "$2" >&2
+    fi
+    exit 1
+}
 
 create_profile() {
     if [ -z "$1" ]; then
-        echo "Error: No profile name provided."
-        echo "Usage: prof create <profile_name> <load_order>"
-        return 1
+        die "Error: No profile name provided." "Usage: prof create <profile_name> <load_order>"
     fi
 
     if [ -z "$2" ]; then
-        echo "Error: No load order provided."
-        echo "Usage: prof create <profile_name> <load_order>"
-        return 1
+        die "Error: No load order provided." "Usage: prof create <profile_name> <load_order>"
     fi
 
     if ! [[ "$2" =~ ^[0-9]+$ ]]; then
-        echo "Error: Load order must be a positive integer."
-        return 1
+        die "Error: Load order must be a positive integer."
     fi
 
     if ! [[ "$1" =~ ^[A-Za-z0-9_-]+$ ]]; then
-        echo "Error: Profile name can only contain letters, numbers, underscores, and hyphens."
-        return 1
+        die "Error: Profile name can only contain letters, numbers, underscores, and hyphens."
     fi
 
     local profile_name=$1
@@ -130,8 +132,7 @@ create_profile() {
 
     # Check if profile already exists
     if grep -qw "$profile_name" ~/.bash_profiles/.profile_metadata; then
-        echo "Profile $profile_name already exists."
-        return
+        die "Profile $profile_name already exists."
     fi
 
     # Add the profile to the metadata file
@@ -150,9 +151,7 @@ create_profile() {
 
 edit_profile() {
     if [ -z "$1" ]; then
-        echo "Error: No profile name provided."
-        echo "Usage: prof edit <profile_name> [new_load_order]"
-        return 1
+        die "Error: No profile name provided." "Usage: prof edit <profile_name> [new_load_order]"
     fi
 
     local profile_name=$1
@@ -160,8 +159,7 @@ edit_profile() {
 
     # Check if the new load order is a positive integer if provided
     if [[ -n "$new_load_order" && ! "$new_load_order" =~ ^[0-9]+$ ]]; then
-        echo "Error: Load order must be a positive integer."
-        return 1
+        die "Error: Load order must be a positive integer."
     fi
 
     # Determine the user's preferred editor
@@ -178,7 +176,7 @@ edit_profile() {
             case "$(uname -s)" in
                 Darwin*)    sed -i '' "s/^.*$profile_name$/$formatted_load_order $profile_name/" ~/.bash_profiles/.profile_metadata ;;
                 Linux*)     sed -i "s/^.*$profile_name$/$formatted_load_order $profile_name/" ~/.bash_profiles/.profile_metadata ;;
-                *)          echo "Unsupported OS" ;;
+                *)          die "Unsupported OS. Cannot determind editor. Edit profiles manually in the ~/.bash_profiles directory." ;;
             esac
 
             # Sort the metadata file by load order
@@ -188,8 +186,7 @@ edit_profile() {
         # Open the profile in the editor
         $editor ~/.bash_profiles/$profile_name
     else
-        echo "Error: Profile $profile_name does not exist."
-        return 1
+        die "Error: Profile $profile_name does not exist."
     fi
 }
 
@@ -197,9 +194,7 @@ edit_profile() {
 
 delete_profile() {
     if [ -z "$1" ]; then
-        echo "Error: No profile name provided."
-        echo "Usage: prof delete <profile_name>"
-        return 1
+        die "Error: No profile name provided." "Usage: prof delete <profile_name>"
     fi
 
     local profile_name=$1
@@ -218,17 +213,16 @@ delete_profile() {
             echo "Deletion canceled."
         fi
     else
-        echo "Error: Profile '$profile_name' does not exist."
-        return 1
+        die "Error: Profile '$profile_name' does not exist."
     fi
 }
 
 
-list_profiles() {
+ist_profiles() {
     # Check if the metadata file exists
     if [ ! -f ~/.bash_profiles/.profile_metadata ]; then
         echo "No profiles found."
-        return 1
+        return 0
     fi
 
     echo "Profiles:"
@@ -247,15 +241,11 @@ export_profile() {
     local export_directory=$2
 
     if [ -z "$profile_name" ]; then
-        echo "Error: No profile name provided."
-        echo "Usage: prof export <profile_name> <export_directory>"
-        return 1
+        die "Error: No profile name provided." "Usage: prof export <profile_name> <export_directory>"
     fi
 
     if [ -z "$export_directory" ]; then
-        echo "Error: No export directory provided."
-        echo "Usage: prof export <profile_name> <export_directory>"
-        return 1
+        die "Error: No export directory provided." "Usage: prof export <profile_name> <export_directory>"
     fi
 
     # Check if the profile exists
@@ -268,8 +258,7 @@ export_profile() {
 
         echo "Profile '$profile_name' exported to $export_directory."
     else
-        echo "Error: Profile '$profile_name' does not exist."
-        return 1
+        die "Error: Profile '$profile_name' does not exist."
     fi
 }
 
@@ -278,25 +267,19 @@ import_profile() {
     local load_order=$2
 
     if [ -z "$profile_file" ]; then
-        echo "Error: No profile file provided."
-        echo "Usage: prof import <profile_file> <load_order>"
-        return 1
+        die "Error: No profile file provided." "Usage: prof import <profile_file> <load_order>"
     fi
 
     if [ -z "$load_order" ]; then
-        echo "Error: No load order provided."
-        echo "Usage: prof import <profile_file> <load_order>"
-        return 1
+        die "Error: No load order provided." "Usage: prof import <profile_file> <load_order>"
     fi
 
     if ! [[ "$load_order" =~ ^[0-9]+$ ]]; then
-        echo "Error: Load order must be a positive integer."
-        return 1
+        die "Error: Load order must be a positive integer."
     fi
 
     if [ ! -f "$profile_file" ]; then
-        echo "Error: Profile file '$profile_file' does not exist."
-        return 1
+        die "Error: Profile file '$profile_file' does not exist."
     fi
 
     local profile_name=$(basename "$profile_file")
@@ -322,9 +305,7 @@ install_prof() {
 
     # Check if the target file exists
     if [ ! -f "$target_file" ]; then
-        echo "Error: Target file '$target_file' does not exist."
-        echo "You can specify a different file by providing an argument, e.g., prof install .zshrc"
-        return 1
+        die "Error: Target file '$target_file' does not exist." "You can specify a different file by providing an argument, e.g., prof install .zshrc"
     fi
 
     # Check if the code already exists in the target file
@@ -418,6 +399,7 @@ main() {
         *)
             echo "Invalid command: $1"
             display_help
+            die
             ;;
     esac
 }
